name: Build and Release TTYImg

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.4" 

      - name: Build Binaries
        run: |
          mkdir -p bin
          platforms=(
            "linux/amd64"
            "linux/arm64"
            "linux/arm"
            "windows/amd64"
            "windows/386"
            "darwin/amd64"
            "darwin/arm64"
          )
          for platform in "${platforms[@]}"; do
            os=$(echo $platform | cut -d'/' -f1)
            arch=$(echo $platform | cut -d'/' -f2)
            output="bin/ttyimg-${os}-${arch}"
            if [ "$os" == "windows" ]; then
              output="${output}.exe"
            fi
            echo "Building for $os/$arch..."
            GOOS=$os GOARCH=$arch go build -o $output
          done

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          release_name: TTYImg ${{ github.ref_name }}
          body: |
            This release contains precompiled binaries for the following platforms:
            - Linux (amd64, arm64, arm)
            - Windows (amd64, 386)
            - macOS (amd64, arm64)
          draft: false
          prerelease: false

      - name: Upload Binaries
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/ttyimg-linux-amd64
          asset_name: ttyimg-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Binaries
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/ttyimg-linux-arm64
          asset_name: ttyimg-linux-arm64
          asset_content_type: application/octet-stream

      - name: Upload Binaries
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/ttyimg-linux-arm
          asset_name: ttyimg-linux-arm
          asset_content_type: application/octet-stream

      - name: Upload Binaries
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/ttyimg-windows-amd64.exe
          asset_name: ttyimg-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Binaries
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/ttyimg-windows-386.exe
          asset_name: ttyimg-windows-386.exe
          asset_content_type: application/octet-stream

      - name: Upload Binaries
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/ttyimg-darwin-amd64
          asset_name: ttyimg-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload Binaries
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/ttyimg-darwin-arm64
          asset_name: ttyimg-darwin-arm64
          asset_content_type: application/octet-stream
